(function(){'use strict';
const D=window.ShiireDecision,J=window.ShiireJan,$=id=>document.getElementById(id),KEY='shiireJudge.v9.items',CAMERA_TIMEOUT_MS=8000;
const state={items:load(),currentJan:null,stream:null,reader:null,controls:null,busy:false,candidate:'',hits:0,hitAt:0};
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]').slice(0,30)}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.items.slice(0,30)))}
function yen(v){const n=Number(v);return Number.isFinite(n)?Math.round(n).toLocaleString('ja-JP')+'円':'-'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function status(t,c=''){$('status').className='status '+c;$('status').textContent=t}
function current(){return state.items.find(x=>String(x.jan)===String(state.currentJan))||null}
function upsert(x){const i=state.items.findIndex(y=>String(y.jan)===String(x.jan)),merged=i>=0?{...state.items[i],...x}:x;if(i>=0)state.items.splice(i,1);state.items.unshift(merged);state.items=state.items.slice(0,30);save();render();return merged}
function patch(jan,values){const x=state.items.find(y=>String(y.jan)===String(jan));if(!x)return null;Object.assign(x,values);save();render();return x}
function render(){const list=$('productList');if(!state.items.length){list.innerHTML='<div class="empty">まだ商品はありません。</div>';return}list.innerHTML=state.items.map(x=>{const r=D.evaluate(x,x.cost||null),g=r.guide;x.signal=r.signal;x.label=r.label;x.reasons=r.reasons;return`<button class="item" data-jan="${esc(x.jan)}" type="button"><span class="signal">${r.signal}</span><span class="thumb">${x.image?`<img src="${esc(x.image)}" alt="">`:'📦'}</span><span class="item-info"><span class="item-name">${esc(x.name||x.keepa?.title||'商品名不明')}</span><span class="meta">JAN ${esc(x.jan)}<br>${esc(r.label)}</span></span><span class="item-side"><b>${g?yen(g.safe)+'以下':'-'}</b><small>安全目安</small><span>詳細</span></span></button>`}).join('');list.querySelectorAll('.item').forEach(b=>b.addEventListener('click',()=>openSheet(b.dataset.jan)));save()}
function stopCamera(){try{state.controls?.stop?.()}catch{}try{state.stream?.getTracks?.().forEach(t=>t.stop())}catch{}state.controls=state.reader=state.stream=null;if($('video'))$('video').srcObject=null}
async function startCamera(){stopCamera();if(!navigator.mediaDevices?.getUserMedia){status('このブラウザではカメラを利用できません','error');return}try{if(!window.ZXingBrowser?.BrowserMultiFormatReader)throw Error('読取機能の準備に失敗しました');status('カメラを起動中…');state.reader=new ZXingBrowser.BrowserMultiFormatReader(undefined,{delayBetweenScanAttempts:120,delayBetweenScanSuccess:250});let timedOut=false;const decoding=state.reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false},$('video'),result=>{if(!result||state.busy)return;const code=J.normalizeJan(result.getText?.()||result.text||'');if(!J.validJan(code)||!accept(code))return;navigator.vibrate?.(60);lookup(code)});decoding.then(c=>{if(timedOut)c?.stop?.()}).catch(()=>{});state.controls=await Promise.race([decoding,new Promise((_,reject)=>setTimeout(()=>{timedOut=true;reject(Error('カメラの応答がありません'))},CAMERA_TIMEOUT_MS))]);state.stream=$('video').srcObject;$('cameraMessage').textContent='JANを緑の枠に大きく合わせてください';status('スキャン待機中','ok')}catch(e){const denied=e?.name==='NotAllowedError';$('cameraMessage').textContent=denied?'カメラの許可を確認してください':'カメラを開始できません';status(denied?'カメラが許可されていません':`カメラを開始できません：${e?.message||'端末を確認してください'}`,'error')}}
function accept(code){const now=Date.now();if(code!==state.candidate||now-state.hitAt>1200){state.candidate=code;state.hits=1;state.hitAt=now;return false}state.hits++;state.hitAt=now;if(state.hits<2)return false;state.candidate='';state.hits=0;return true}
async function manualLookup(){const code=J.normalizeJan($('manualJan').value);$('manualJan').value=code;if(!J.validJan(code)){status('JANコードを確認してください','warn');return}await lookup(code)}
async function lookup(jan){if(state.busy)return;state.busy=true;$('manualJan').value=jan;status('商品データを確認中…');try{const r=await fetch('/api/product?jan='+encodeURIComponent(jan),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'商品検索エラー');if(!d.found){status('商品データが見つかりませんでした','warn');return}upsert({...d,jan,scannedAt:Date.now(),keepaStatus:'loading'});status('商品を特定しました。Keepa確認中…','ok');await fetchKeepa(jan,true)}catch(e){status('商品データを取得できません：'+e.message,'error')}finally{state.busy=false}}
async function fetchKeepa(jan,openAfter=false){$('keepaStatus').className='status';$('keepaStatus').textContent='Keepa：取得中…';try{const r=await fetch('/api/keepa?jan='+encodeURIComponent(jan),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Keepa取得エラー');if(!d.found){patch(jan,{keepaStatus:'notfound',keepa:null});$('keepaStatus').className='status warn';$('keepaStatus').textContent='Keepa：Amazon商品が見つかりません';return}patch(jan,{keepaStatus:'ok',keepa:d.product,keepaFetchedAt:Date.now()});$('keepaStatus').className='status ok';$('keepaStatus').textContent=`Keepa：接続中（残り ${d.tokensLeft??'-'} token）`;if(openAfter)openSheet(jan)}catch(e){$('keepaStatus').className='status error';$('keepaStatus').textContent='Keepa：取得エラー（'+e.message+'）'}}
function openSheet(jan){state.currentJan=jan;const x=current();if(!x)return;$('detailName').textContent=x.name||x.keepa?.title||'商品名不明';$('detailMeta').textContent=`JAN ${x.jan}${x.keepa?.asin?' / ASIN '+x.keepa.asin:''}`;$('detailImage').innerHTML=x.image?`<img src="${esc(x.image)}" alt="">`:'📦';$('costInput').value=x.cost?Number(x.cost).toLocaleString('ja-JP'):'';fillStats(x);updateVerdict();$('modal').classList.add('open');document.body.style.overflow='hidden'}
function fillStats(x){const k=x.keepa||{},g=D.canonicalSafeGuide(x);$('statCurrent').textContent=yen(k.newPrice);$('statAverage').textContent=yen(k.avg90New);$('statOffers').textContent=Number.isFinite(Number(k.newOfferCount))?k.newOfferCount+'人':'-';$('statDemand').textContent=Number.isFinite(Number(k.monthlySold))?k.monthlySold+'/月':Number.isFinite(Number(k.salesRankDrops30))?k.salesRankDrops30+'回':'-';$('statAmazon').textContent=k.amazonPresent?'あり':'なし';$('statFba').textContent=yen(k.fbaFee);$('safeGuide').textContent=g?yen(g.safe)+'以下':'-';$('currentGuide').textContent=g?yen(g.currentSafe)+'以下':'-';$('averageGuide').textContent=g?yen(g.ninetySafe)+'以下':'-'}
function money(v){const n=Number(String(v||'').replace(/\D/g,''));return Number.isFinite(n)&&n>0?n:null}
function updateVerdict(){const x=current();if(!x)return;const cost=money($('costInput').value);x.cost=cost;const r=D.evaluate(x,cost),d=r.decision;x.signal=r.signal;x.label=r.label;x.reasons=r.reasons;$('verdict').className='verdict '+(r.signal==='🟢'?'green':'red');$('verdictSignal').textContent=r.signal;$('verdictTitle').textContent=cost?r.label:'仕入れ価格を入力';$('profit').textContent=d?yen(d.profit):'-';$('margin').textContent=d?d.margin+'%':'-';$('roi').textContent=d?d.roi+'%':'-';$('fees').textContent=d?yen(d.fees):'-';const demand=D.demandLevel(x.keepa),qty=r.signal==='🟢'?Math.max(1,Math.min(5,demand===3?5:demand===2?3:1)):0;$('quantity').textContent='推奨 '+qty+'個まで';$('reasons').innerHTML=(r.signal==='🟢'?['利益・回転・競合・価格安定・商品一致を確認済み']:r.reasons).map(v=>`<span class="reason">${esc(v)}</span>`).join('');save();render()}
function formatCost(){const cost=money($('costInput').value);$('costInput').value=cost?cost.toLocaleString('ja-JP'):'';updateVerdict()}
function closeSheet(){$('modal').classList.remove('open');document.body.style.overflow='';state.currentJan=null}
async function loadNearby(){const x=current(),list=$('nearbyList');if(!x)return;if(!x.brand){list.textContent='ブランド情報がないため検索できません';return}$('nearbyButton').disabled=true;list.textContent='候補を確認中…';try{const r=await fetch(`/api/related?brand=${encodeURIComponent(x.brand)}&jan=${encodeURIComponent(x.jan)}&name=${encodeURIComponent(x.name||'')}`),d=await r.json();if(!r.ok)throw Error();const cs=(d.candidates||[]).slice(0,3);list.innerHTML=cs.length?cs.map(c=>`<div class="near-item"><b>${esc(c.name||'')}</b><br>${c.greenMax?yen(c.greenMax)+'以下なら候補':'詳細で確認'}</div>`).join(''):'この棚の候補はありません'}catch{list.textContent='この棚の候補を取得できませんでした'}finally{$('nearbyButton').disabled=false}}
let worker=null;async function readScreenJan(){$('ocrButton').disabled=true;try{const v=$('video');if(!v.videoWidth)throw Error('カメラ映像がありません');if(!window.Tesseract)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});if(!worker){status('JAN文字読取を準備中…');worker=await Tesseract.createWorker('eng');await worker.setParameters({tessedit_char_whitelist:'0123456789'})}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);status('JAN文字を確認中…');const out=await worker.recognize(c),code=J.extractJanFromText(out?.data?.text||'');if(!code)throw Error('JAN文字を読めませんでした');$('manualJan').value=code;await lookup(code)}catch(e){status(e.message+'。文字を大きく映して再試行してください','warn')}finally{$('ocrButton').disabled=false}}
$('cameraButton').addEventListener('click',startCamera);$('ocrButton').addEventListener('click',readScreenJan);$('searchButton').addEventListener('click',manualLookup);$('manualJan').addEventListener('keydown',e=>{if(e.key==='Enter')manualLookup()});$('costInput').addEventListener('input',formatCost);$('clearButton').addEventListener('click',()=>{state.items=[];save();render()});$('closeButton').addEventListener('click',closeSheet);$('refreshButton').addEventListener('click',()=>{const x=current();if(x)fetchKeepa(x.jan,true)});$('nearbyButton').addEventListener('click',loadNearby);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeSheet()});window.addEventListener('pagehide',stopCamera);render();startCamera();
})();
