(function(){'use strict';
const Core=window.SedoriGoCore;
const $=id=>document.getElementById(id);
const CACHE_KEY='sedoriGo.candidates.v1';
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function yen(value){const n=Number(value);return Number.isFinite(n)&&n>0?`${Math.round(n).toLocaleString('ja-JP')}円`:'-';}
function loadCache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null')}catch{return null}}
function saveCache(shortlist,meta){try{localStorage.setItem(CACHE_KEY,JSON.stringify({savedAt:Date.now(),shortlist,meta}))}catch{}}
function setStatus(text,kind=''){const el=$('candidateStatus');if(!el)return;el.className='candidate-status '+kind;el.textContent=text;}
function demandText(item){if(Number.isFinite(Number(item.monthlySold)))return `${Number(item.monthlySold).toLocaleString('ja-JP')}/月`;if(Number.isFinite(Number(item.salesRank)))return `Rank ${Number(item.salesRank).toLocaleString('ja-JP')}`;return '-';}
function render(shortlist){const list=$('candidateList');if(!list)return;if(!shortlist.length){list.innerHTML='<div class="candidate-empty">条件に合う店頭確認候補はありませんでした。</div>';return;}list.innerHTML=shortlist.map(item=>`<article class="candidate-card"><div class="candidate-card-head"><div><span class="candidate-badge">${esc(item.decisionLabel)}</span><h3>${esc(item.title||'商品名不明')}</h3><div class="candidate-jan">JAN ${esc(item.jan)}</div></div><strong class="candidate-limit">${yen(item.preliminarySafeLimit)}<small>仕入れ上限目安</small></strong></div><div class="candidate-metrics"><span>Amazon新品<b>${yen(item.newPrice)}</b></span><span>90日平均<b>${yen(item.avg90New)}</b></span><span>回転<b>${esc(demandText(item))}</b></span><span>出品者<b>${Number.isFinite(Number(item.newOfferCount))?esc(String(item.newOfferCount))+'人':'-'}</b></span></div><p class="candidate-note">候補探索用の目安です。現物・店頭価格を確認して最終判断してください。</p><button class="candidate-check-button" type="button" data-jan="${esc(item.jan)}">${esc(item.actionLabel)}</button></article>`).join('');list.querySelectorAll('.candidate-check-button').forEach(button=>button.addEventListener('click',()=>{const input=$('manualJan'),search=$('searchButton');if(!input||!search)return;input.value=button.dataset.jan;search.click();document.querySelector('.camera-card')?.scrollIntoView({behavior:'smooth',block:'start'});}));}
async function discover(){const button=$('candidateSearchButton');if(!button)return;button.disabled=true;setStatus('候補を絞り込んでいます…');try{const finderResponse=await fetch('/api/candidates',{cache:'no-store'});const finder=await finderResponse.json();if(!finderResponse.ok){if(finderResponse.status===429||finder.error==='token_limit')throw Object.assign(new Error('Keepa利用上限のため候補を更新できません'),{kind:'warn'});throw new Error('候補探索データを取得できません');}const asins=(finder.candidates||[]).slice(0,5);if(!asins.length){render([]);setStatus('候補は見つかりませんでした','ok');return;}const detailResponse=await fetch('/api/candidate-details?asins='+encodeURIComponent(asins.join(',')),{cache:'no-store'});const detail=await detailResponse.json();if(!detailResponse.ok){if(detailResponse.status===429||detail.error==='token_limit')throw Object.assign(new Error('Keepa利用上限のため候補詳細を更新できません'),{kind:'warn'});throw new Error('候補詳細を取得できません');}const shortlist=Core.buildShortlist(detail.details||[]);saveCache(shortlist,{finderTokens:finder.tokensConsumed??null,detailTokens:detail.tokensConsumed??null,totalResults:finder.totalResults??null});render(shortlist);setStatus(`店頭確認候補 ${shortlist.length}件を更新しました`,'ok');}catch(error){setStatus(error.message||'候補探索に失敗しました',error.kind||'error');}finally{button.disabled=false;}}
function init(){const button=$('candidateSearchButton');if(!button||!Core)return;button.addEventListener('click',discover);const cache=loadCache();if(Core.isFreshCandidateCache(cache)){render(cache.shortlist);setStatus('6時間以内の保存候補を表示しています','ok');}else{render([]);setStatus('必要なときだけ「候補を探す」を押してください');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
